/* Pharmacy schema for SQL Server — table name [USER] is quoted because USER is reserved. */
IF OBJECT_ID(N'[dbo].[PAYMENT]', N'U') IS NOT NULL DROP TABLE [dbo].[PAYMENT];
IF OBJECT_ID(N'[dbo].[ORDER_ITEM]', N'U') IS NOT NULL DROP TABLE [dbo].[ORDER_ITEM];
IF OBJECT_ID(N'[dbo].[ORDER]', N'U') IS NOT NULL DROP TABLE [dbo].[ORDER];
IF OBJECT_ID(N'[dbo].[PRESCRIPTION_ITEM]', N'U') IS NOT NULL DROP TABLE [dbo].[PRESCRIPTION_ITEM];
IF OBJECT_ID(N'[dbo].[PRESCRIPTION]', N'U') IS NOT NULL DROP TABLE [dbo].[PRESCRIPTION];
IF OBJECT_ID(N'[dbo].[MED_SIDE_EFFECT]', N'U') IS NOT NULL DROP TABLE [dbo].[MED_SIDE_EFFECT];
IF OBJECT_ID(N'[dbo].[MED_HEALING_EFFECT]', N'U') IS NOT NULL DROP TABLE [dbo].[MED_HEALING_EFFECT];
IF OBJECT_ID(N'[dbo].[MEDICINE]', N'U') IS NOT NULL DROP TABLE [dbo].[MEDICINE];
IF OBJECT_ID(N'[dbo].[PATIENT_ALLERGY]', N'U') IS NOT NULL DROP TABLE [dbo].[PATIENT_ALLERGY];
IF OBJECT_ID(N'[dbo].[PATIENT]', N'U') IS NOT NULL DROP TABLE [dbo].[PATIENT];
IF OBJECT_ID(N'[dbo].[EMPLOYEE]', N'U') IS NOT NULL DROP TABLE [dbo].[EMPLOYEE];
IF OBJECT_ID(N'[dbo].[USER_ROLE]', N'U') IS NOT NULL DROP TABLE [dbo].[USER_ROLE];
IF OBJECT_ID(N'[dbo].[USER]', N'U') IS NOT NULL DROP TABLE [dbo].[USER];
IF OBJECT_ID(N'[dbo].[ROLE]', N'U') IS NOT NULL DROP TABLE [dbo].[ROLE];
GO

CREATE TABLE [dbo].[ROLE] (
    RoleID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    RoleName NVARCHAR(100) NOT NULL,
    PermissionsLevel INT NOT NULL,
    Description NVARCHAR(500) NULL
);

CREATE TABLE [dbo].[USER] (
    UserID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    Username NVARCHAR(100) NOT NULL UNIQUE,
    [Password] NVARCHAR(256) NOT NULL,
    Email NVARCHAR(200) NULL,
    Phone NVARCHAR(50) NULL,
    IsActive BIT NOT NULL CONSTRAINT DF_User_IsActive DEFAULT (1)
);

CREATE TABLE [dbo].[USER_ROLE] (
    UserID INT NOT NULL,
    RoleID INT NOT NULL,
    CONSTRAINT PK_USER_ROLE PRIMARY KEY (UserID, RoleID),
    CONSTRAINT FK_USER_ROLE_USER FOREIGN KEY (UserID) REFERENCES [dbo].[USER](UserID) ON DELETE CASCADE,
    CONSTRAINT FK_USER_ROLE_ROLE FOREIGN KEY (RoleID) REFERENCES [dbo].[ROLE](RoleID) ON DELETE CASCADE
);

CREATE TABLE [dbo].[PATIENT] (
    UserID INT NOT NULL PRIMARY KEY,
    Age REAL NOT NULL,
    Address NVARCHAR(500) NULL,
    PatientBalance DECIMAL(18,2) NOT NULL CONSTRAINT DF_Patient_Bal DEFAULT (0),
    CONSTRAINT FK_PATIENT_USER FOREIGN KEY (UserID) REFERENCES [dbo].[USER](UserID) ON DELETE CASCADE
);

CREATE TABLE [dbo].[PATIENT_ALLERGY] (
    UserID INT NOT NULL,
    AllergyName NVARCHAR(200) NOT NULL,
    CONSTRAINT PK_PATIENT_ALLERGY PRIMARY KEY (UserID, AllergyName),
    CONSTRAINT FK_ALLERGY_PATIENT FOREIGN KEY (UserID) REFERENCES [dbo].[PATIENT](UserID) ON DELETE CASCADE
);

CREATE TABLE [dbo].[EMPLOYEE] (
    UserID INT NOT NULL PRIMARY KEY,
    Salary DECIMAL(18,2) NOT NULL,
    JobType NVARCHAR(50) NOT NULL,
    CONSTRAINT FK_EMPLOYEE_USER FOREIGN KEY (UserID) REFERENCES [dbo].[USER](UserID) ON DELETE CASCADE
);

CREATE TABLE [dbo].[MEDICINE] (
    MedicineID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    Name NVARCHAR(200) NOT NULL,
    Price DECIMAL(18,2) NOT NULL,
    Category NVARCHAR(100) NULL,
    ExpiryDate DATE NOT NULL,
    StockQuantity INT NOT NULL,
    UsageInstructions NVARCHAR(MAX) NULL,
    IsRefundable BIT NOT NULL DEFAULT (0)
);

CREATE TABLE [dbo].[MED_SIDE_EFFECT] (
    MedicineID INT NOT NULL,
    SideEffectName NVARCHAR(200) NOT NULL,
    CONSTRAINT PK_MED_SIDE PRIMARY KEY (MedicineID, SideEffectName),
    CONSTRAINT FK_MED_SIDE_MED FOREIGN KEY (MedicineID) REFERENCES [dbo].[MEDICINE](MedicineID) ON DELETE CASCADE
);

CREATE TABLE [dbo].[MED_HEALING_EFFECT] (
    MedicineID INT NOT NULL,
    HealingEffectName NVARCHAR(200) NOT NULL,
    CONSTRAINT PK_MED_HEAL PRIMARY KEY (MedicineID, HealingEffectName),
    CONSTRAINT FK_MED_HEAL_MED FOREIGN KEY (MedicineID) REFERENCES [dbo].[MEDICINE](MedicineID) ON DELETE CASCADE
);

CREATE TABLE [dbo].[ORDER] (
    OrderID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    OrderDate DATETIME2 NOT NULL DEFAULT (SYSUTCDATETIME()),
    TotalPrice DECIMAL(18,2) NOT NULL,
    Status NVARCHAR(50) NOT NULL,
    PatientID INT NOT NULL,
    CashierID INT NULL,
    CONSTRAINT FK_ORDER_PATIENT FOREIGN KEY (PatientID) REFERENCES [dbo].[PATIENT](UserID),
    CONSTRAINT FK_ORDER_CASHIER FOREIGN KEY (CashierID) REFERENCES [dbo].[USER](UserID)
);

CREATE TABLE [dbo].[ORDER_ITEM] (
    OrderID INT NOT NULL,
    MedicineID INT NOT NULL,
    Quantity INT NOT NULL,
    UnitPrice DECIMAL(18,2) NOT NULL,
    CONSTRAINT PK_ORDER_ITEM PRIMARY KEY (OrderID, MedicineID),
    CONSTRAINT FK_OI_ORDER FOREIGN KEY (OrderID) REFERENCES [dbo].[ORDER](OrderID) ON DELETE CASCADE,
    CONSTRAINT FK_OI_MED FOREIGN KEY (MedicineID) REFERENCES [dbo].[MEDICINE](MedicineID)
);

CREATE TABLE [dbo].[PRESCRIPTION] (
    PrescriptionID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    IssueDate DATETIME2 NOT NULL DEFAULT (SYSUTCDATETIME()),
    Status NVARCHAR(50) NOT NULL,
    PatientID INT NOT NULL,
    PharmacistID INT NULL,
    CONSTRAINT FK_PRE_PATIENT FOREIGN KEY (PatientID) REFERENCES [dbo].[PATIENT](UserID),
    CONSTRAINT FK_PRE_PHARM FOREIGN KEY (PharmacistID) REFERENCES [dbo].[USER](UserID)
);

CREATE TABLE [dbo].[PRESCRIPTION_ITEM] (
    PrescriptionID INT NOT NULL,
    MedicineID INT NOT NULL,
    PrescribedQuantity INT NOT NULL,
    CONSTRAINT PK_PRE_ITEM PRIMARY KEY (PrescriptionID, MedicineID),
    CONSTRAINT FK_PI_PRE FOREIGN KEY (PrescriptionID) REFERENCES [dbo].[PRESCRIPTION](PrescriptionID) ON DELETE CASCADE,
    CONSTRAINT FK_PI_MED FOREIGN KEY (MedicineID) REFERENCES [dbo].[MEDICINE](MedicineID)
);

CREATE TABLE [dbo].[PAYMENT] (
    PaymentID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    Amount DECIMAL(18,2) NOT NULL,
    PaymentDate DATETIME2 NOT NULL DEFAULT (SYSUTCDATETIME()),
    PaymentMethod NVARCHAR(50) NULL,
    Status NVARCHAR(50) NOT NULL,
    OrderID INT NOT NULL UNIQUE,
    CONSTRAINT FK_PAY_ORDER FOREIGN KEY (OrderID) REFERENCES [dbo].[ORDER](OrderID)
);
GO

INSERT INTO [dbo].[ROLE] (RoleName, PermissionsLevel, Description) VALUES
 (N'Patient', 1, N'Patient role'),
 (N'Pharmacist', 50, N'Pharmacist'),
 (N'Cashier', 40, N'Cashier'),
 (N'Admin', 100, N'Administrator');
GO
